version: '3'

services:
  service:
    container_name: service
    image: poiu694/gdsc-uos-recruit-service:latest
    restart: always
    build:
      context: .
      dockerfile: ./apps/service/Dockerfile
    ports:
      - '3000:3000'
