version: "3"

services:
  # admin:
  #   container_name: admin
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - BUILD_CONTEXT=admin
  #   ports:
  #     - "8080:80"
  service:
    container_name: service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=service
        - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - "./service/next:/usr/src/app/service/next"
      - "./service/node_modules:/usr/src/app/service/node_modules"
      - "./:/usr/src/app/service"
