name: ci-action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop

jobs:
  lint-and-test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout action
        uses: actions/checkout@v2

      - name: checkout pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: file changes action
        uses: trilom/file-changes-action@master

      - name: save variable output files
        run: |
          echo "OUTPUT_FILES=$(cat $HOME/files.json)" >> $GITHUB_OUTPUT
        id: files

      - name: save target files
        run: |
          if [[ "${{ steps.files.outputs.OUTPUT_FILES }}" == *"service"* ]]; then
            echo "service=true" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ steps.files.outputs.OUTPUT_FILES }}" == *"admin"* ]]; then
            echo "admin=true" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ steps.files.outputs.OUTPUT_FILES }}" == *"api"* ]]; then
            echo "api=true" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ steps.files.outputs.OUTPUT_FILES }}" == *"design-system"* ]]; then
            echo "ui=true" >> $GITHUB_OUTPUT
          fi
        id: changes

      - name: pnpm install
        run: pnpm install

      - name: run service eslint
        if: ${{ steps.changes.outputs.service == 'true' }}
        run: |
          pnpm run lint --filter='@gdsc-uos/service'

      - name: run admin eslint
        if: ${{ steps.changes.outputs.admin == 'true' }}
        run: |
          pnpm run lint --filter='@gdsc-uos/admin'

      - name: run ui eslint
        if: ${{ steps.changes.outputs.ui == 'true' }}
        run: |
          pnpm run lint --filter='@gdsc-uos/ui'

      - name: run api eslint
        if: ${{ steps.changes.outputs.api == 'true' }}
        run: |
          pnpm run lint --filter='@gdsc-uos/api'
